version: 2
jobs:
  build:
    macos:
      # specify the version you desire here
      xcode: "9.0"
#    working_directory: ~/residence
    steps:
      - checkout

      - run:
        name: Install Gems
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
      macos:
        xcode: "9.0"

      steps:
        - checkout

        # Set up code signing via Fastlane Match.
        - run:
            name: Set up code signing
            command: fastlane match development --readonly

        # Build the release version of the app.
        - run:
            name: Build IPA
            command: fastlane gym

        # Deploy!
        - run:
            name: Deploy to App Store
            command: fastlane ios beta

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
